from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from neo_api_client import NeoAPI
from app.api.deps import get_current_user
from app.core.database import get_collection

router = APIRouter()

class KotakCredentials(BaseModel):
    name: str; mobile: str; ucc: str; mpin: str; totp: str; consumer_key: str

class KotakTotpOnly(BaseModel):
    totp: str

# 🟢 STRICT VERIFICATION & TOKEN EXTRACTOR
def verify_and_get_token(client):
    try:
        # Dummy API Call to verify login
        client.quotes(instrument_tokens=[{"instrument_token": "256265", "exchange_segment": "nse_cm"}], quote_type="all")
        
        # Extract Token (Kotak library usually stores it as bearer_token or access_token)
        token = getattr(client, "bearer_token", None)
        if not token:
            token = getattr(client, "access_token", None)
            
        if not token:
            raise Exception("Login success but Token not generated by Kotak. Try again.")
            
        return token
    except TypeError as te:
        if "NoneType" in str(te) or "str" in str(te):
            raise Exception("TOTP Expired! Kripya Google Authenticator se ekdum fresh TOTP daalein.")
    except Exception as e:
        raise Exception(f"Login Verification Failed: {str(e)}")


@router.post("/kotak-login")
async def connect_kotak_full(creds: KotakCredentials, current_user: dict = Depends(get_current_user)):
    try:
        client = NeoAPI(consumer_key=creds.consumer_key, environment='prod')
        client.totp_login(mobile_number=creds.mobile, ucc=creds.ucc, totp=creds.totp)
        client.totp_validate(mpin=creds.mpin)
        
        # 🟢 Token nikal kar DB me daalenge
        bearer_token = verify_and_get_token(client) 

        users_col = get_collection("users")
        await users_col.update_one({"id": current_user["id"]}, {"$set": {
            "kotak_status": "Active", 
            "kotak_name": creds.name, 
            "kotak_ucc": creds.ucc,
            "kotak_consumer_key": creds.consumer_key, 
            "kotak_mobile": creds.mobile, 
            "kotak_mpin": creds.mpin,
            "kotak_bearer_token": bearer_token # 💾 SAVED TO MONGODB
        }})
        return {"status": "success", "message": "✅ Kotak Neo Connected & Token Saved!", "ucc": creds.ucc}
    except Exception as e: raise HTTPException(status_code=400, detail=str(e))


@router.post("/kotak-totp-login")
async def connect_kotak_quick(req: KotakTotpOnly, current_user: dict = Depends(get_current_user)):
    try:
        users_col = get_collection("users")
        user_data = await users_col.find_one({"id": current_user["id"]})
        if not user_data or user_data.get("kotak_status") != "Active": raise Exception("Broker profile not found.")

        client = NeoAPI(consumer_key=user_data.get("kotak_consumer_key"), environment='prod')
        client.totp_login(mobile_number=user_data.get("kotak_mobile"), ucc=user_data.get("kotak_ucc"), totp=req.totp)
        client.totp_validate(mpin=user_data.get("kotak_mpin"))
        
        # 🟢 Token nikal kar DB me daalenge
        bearer_token = verify_and_get_token(client)

        await users_col.update_one({"id": current_user["id"]}, {"$set": {
            "kotak_bearer_token": bearer_token # 💾 UPDATED IN MONGODB
        }})
        
        return {"status": "success", "message": "✅ Token Generated! Session Started."}
    except Exception as e: raise HTTPException(status_code=400, detail=str(e))
